#This file is to train specific folders from the dataset

# Ultralytics YOLO ğŸš€, AGPL-3.0 license
# COCO8 dataset (first 8 images from COCO train2017) by Ultralytics
# Documentation: https://docs.ultralytics.com/datasets/detect/coco8/
# Example usage: yolo train data=coco8.yaml
# parent
# â”œâ”€â”€ ultralytics
# â””â”€â”€ datasets
#     â””â”€â”€ coco8  â† downloads here (1 MB)

# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: /home/cleavon/Desktop/YOLOv8/data/fsoco_bounding_boxes_train # dataset root dir
train: amz/images # train images (relative to 'path') 
val: amz/images # val images (relative to 'path') 4 images
# test: # test images (optional)

# Classes
names:
  0: yellow_cone
  1: orange_cone
  2: large_orange_cone
  3: blue_cones
  4: other_cone
  5: unknown_cone
